---
- name: "add node 13.x repo"
  become: yes
  shell: curl -sL https://deb.nodesource.com/setup_13.x | bash -

- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install unzip & node"
  become: yes
  apt:
    pkg:
    - 'unzip'
    - 'nodejs'

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
  
- name: "configure environment Variables"
  become: yes
  lineinfile:
    path: /etc/environment
    line: "{{ item }}"
  loop:
    - "ENVIRONMENT={{ lookup('env', 'ENVIRONMENT') }}"
    - "TYPEORM_CONNECTION={{ lookup('env', 'TYPEORM_CONNECTION') }}"
    - "TYPEORM_ENTITIES={{ lookup('env', 'TYPEORM_ENTITIES') }}"
    - "TYPEORM_HOST={{ lookup('env', 'TYPEORM_HOST') }}"
    - "TYPEORM_PORT={{ lookup('env', 'TYPEORM_PORT') }}"
    - "TYPEORM_USERNAME={{ lookup('env', 'TYPEORM_USERNAME') }}"
    - "TYPEORM_PASSWORD={{ lookup('env', 'TYPEORM_PASSWORD') }}"
    - "TYPEORM_DATABASE={{ lookup('env', 'TYPEORM_DATABASE') }}"
    - "NODE_ENV=production"